# Generated by Django 6.0.7 on 2026-10-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecAuth_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secauth_model',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
